AnnouncementWebSite/Models/Entities/Announcement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnnouncementWebSite.Models.Entities
{
    public class Announcement
    {
        public Announcement()
        { }

        public int Id { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string PhoneNumber { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}

AnnouncementWebSite/ViewModels/Announcements/AddAnnouncementViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AnnouncementWebSite.ViewModels.Announcements
{
    public class AddAnnouncementViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        public string Title { get; set; }
        [Required]
        [StringLength(1000, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 20)]
        public string ShortDescription { get; set; }
        [Required]
        [StringLength(5000, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 30)]
        public string Description { get; set; }
        [Required]
        [Phone]
        [Display(Name = "Phone number")]
        public string PhoneNumber { get; set; }
    }
}

AnnouncementWebSite/ViewModels/Announcements/CardAnnouncementViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnnouncementWebSite.ViewModels.Announcements
{
    public class CardAnnouncementViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
    }
}

AnnouncementWebSite/ViewModels/Announcements/DetailsAnnouncementViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnnouncementWebSite.ViewModels.Announcements
{
    public class DetailsAnnouncementViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string PhoneNumber { get; set; }
        public DateTime CreatedAt { get; set; }
        public List<CardAnnouncementViewModel> SimilarAnnouncements { get; set; }
    }
}

AnnouncementWebSite/ViewModels/Announcements/EditAnnouncementViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnnouncementWebSite.ViewModels.Announcements
{
    public class EditAnnouncementViewModel:AddAnnouncementViewModel
    {
        public int Id { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}

AnnouncementWebSite/Controllers/AnnouncementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AnnouncementWebSite.Models.Entities;
using AnnouncementWebSite.Models.Repos.Interfaces;
using AnnouncementWebSite.ViewModels.Announcements;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NLog;

namespace AnnouncementWebSite.Controllers
{
    public class AnnouncementsController : Controller
    {
        private readonly IAnnouncementRepo _announcementRepo;
        private readonly ILogger<AnnouncementsController> _logger;
        private readonly IMapper _mapper;

        public AnnouncementsController(IAnnouncementRepo announcementRepo, IMapper mapper, ILogger<AnnouncementsController> logger)
        {
            _announcementRepo = announcementRepo;
            _logger = logger;
            this._mapper = mapper;
        }

        public IActionResult GetById(int id)
        {
            Announcement ann = null;
            try
            {
                ann = _announcementRepo.GetById(id);
                
            }
            catch (ArgumentException e)
            {
                _logger.LogWarning(e.Message);
                ViewBag.ErrorMessage = e.Message;
                return View("StatusCodes/NotFound");
            }

            var model = _mapper.Map<DetailsAnnouncementViewModel>(ann);
            model.SimilarAnnouncements =
                GetSimilarAnnouncements(ann).Select(a => _mapper.Map<CardAnnouncementViewModel>(a)).ToList();
            return View("Details",model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(AddAnnouncementViewModel model)
        {
            if (ModelState.IsValid)
            {
                var announcement = _mapper.Map<Announcement>(model);
                announcement.CreatedAt = DateTime.Now;
                try
                {
                    _announcementRepo.Add(announcement);
                }
                catch (ArgumentNullException e)
                {
                    ViewBag.ErrorMessage = e.Message;
                    _logger.LogWarning(e.Message);
                    throw;
                }
                return RedirectToAction("GetById", new { id = announcement.Id });
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Announcement ann = null;
            try
            {
                ann = _announcementRepo.GetById(id);
            }
            catch (ArgumentException e)
            {
                ViewBag.ErrorMessage = e.Message;
                _logger.LogWarning(e.Message);
                return View("StatusCodes/NotFound", id);
            }

            var model = _mapper.Map<EditAnnouncementViewModel>(ann);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(EditAnnouncementViewModel model)
        {
            if (ModelState.IsValid)
            {
                var announcement = _mapper.Map<Announcement>(model);
                try
                {
                    _announcementRepo.Edit(announcement);
                }
                catch (ArgumentException e)
                {
                    ViewBag.ErrorMessage = e.Message;
                    _logger.LogWarning(e.Message);
                    return View("StatusCodes/NotFound", announcement.Id);
                }
                return RedirectToAction("GetById", new {id = announcement.Id});
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {
                _announcementRepo.Delete(id);
            }
            catch (ArgumentException e)
            {
                ViewBag.ErrorMessage = e.Message;
                _logger.LogWarning(e.Message);
                return View("StatusCodes/NotFound", id);
            }
            return RedirectToAction("Index", "Home");
        }

        private IEnumerable<Announcement> GetSimilarAnnouncements(Announcement announcement)
        {
            List<Announcement> res = new List<Announcement>();
            foreach (var ann in _announcementRepo.GetList().Where(a => a.Id != announcement.Id))
            {
                if (ann.Description.ToLower().Split(' ').Where(w => w.Length > 3).Intersect(announcement.Description.ToLower().Split(' ').Where(w => w.Length > 3)).Count() != 0 &&
                    ann.Title.ToLower().Split(' ').Where(w => w.Length > 3).Intersect(announcement.Title.ToLower().Split(' ').Where(w => w.Length > 3)).Count() != 0)
                {
                    res.Add(ann);
                }
            }

            return res.Take(3);
        }
    }
}

AnnouncementWebSite/Views/Announcements/Create.cshtml
@model AddAnnouncementViewModel

<form enctype="multipart/form-data" asp-controller="Announcements" asp-action="Create" method="post" class="mt-3">
    <div class="form-group col-xl-12">
        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" placeholder="Title">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ShortDescription">Short description</label>
            <textarea class="form-control" asp-for="ShortDescription" rows="2"></textarea>
            <span asp-validation-for="ShortDescription" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <textarea class="form-control" asp-for="Description" rows="4"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PhoneNumber"></label>
            <input asp-for="PhoneNumber" class="form-control" aria-describedby="phonelHelp" placeholder="Enter phone number" />
            <small id="phoneHelp" class="form-text text-muted">We'll never share your phone number with anyone else.</small>
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row col-xl-12">
        <div class="form-group col-md-4">
            <button type="submit" class="btn btn-primary m-1">Create</button>
            <a asp-action="Index" asp-controller="Home" class="btn btn-dark m-1">Cancel</a>
        </div>
    </div>
    @section Scripts
    {
        <partial name="_ValidationScriptsPartial"/>
        <script>
                $.validator.methods.range = function (value, element, param) {
                    var globalizedValue = value.replace(",", ".");
                    return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
                }
                $.validator.methods.number = function (value, element) {
                    return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
                }
        </script>
        <script>
                $(document).ready(function () {
                    $('.custom-file-input').on("change",
                        function () {
                            var fileName = $(this).val().split("\\").pop();
                            $(this).next('.custom-file-label').html(fileName);
                        });
                });
        </script>
    }
</form>

AnnouncementWebSite/Views/Announcements/Details.cshtml
@using System.Security.Cryptography
@model DetailsAnnouncementViewModel

    <div>
        <div class="card mt-4">
            <div class="card-header">@Model.Title</div>
            <div class="card-body">
                <p>Created on @Model.CreatedAt.ToString("dd/MM/yyyy")</p>
                <hr/>
                <p class="card-text">@Model.Description</p>
                <h5>Contacts: @Model.PhoneNumber</h5>
                <div class="text-center">
                    <a asp-controller="Home" asp-action="Index"
                       class="btn btn-outline-dark m-1" id="BikeCardBtn">See all</a>
                    <a asp-controller="Announcements" asp-action="Edit" asp-route-id="@Model.Id"
                       class="btn btn-outline-secondary m-1" id="BikeCardBtn">Edit</a>
                    <form method="post" asp-controller="Announcements" asp-action="Delete" asp-route-id="@Model.Id" style="display: inline">
                        <button type="submit" class="btn btn-outline-danger m-1" id="BikeCardBtn"
                                onclick="return confirm('Are you sure you want to delete announcement : @Model.Title')">
                            Delete
                        </button>
                    </form>
                </div>
            </div>
        </div>
        <h3>Similar announcements</h3>
        @if (Model.SimilarAnnouncements.Any())
        {
            <div class="card-deck row">
                @foreach (var a in Model.SimilarAnnouncements)
                {
                    <partial name="AnnouncementCard" for="@a"/>
                }
            </div>
        }
        else
        {
            <h3>There are no similar announcement.</h3>
        }
    </div>

AnnouncementWebSite/Views/Announcements/Edit.cshtml
@model EditAnnouncementViewModel

<form enctype="multipart/form-data" asp-controller="Announcements" asp-action="Edit" method="post" class="mt-3">
    <input hidden asp-for="Id" />
    <input hidden asp-for="CreatedAt"/>
    <div class="form-group col-xl-12">
        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" placeholder="Title">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ShortDescription">Short description</label>
            <textarea class="form-control" asp-for="ShortDescription" rows="2"></textarea>
            <span asp-validation-for="ShortDescription" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <textarea class="form-control" asp-for="Description" rows="4"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PhoneNumber"></label>
            <input asp-for="PhoneNumber" class="form-control" aria-describedby="phonelHelp" placeholder="Enter phone number" />
            <small id="phoneHelp" class="form-text text-muted">We'll never share your phone number with anyone else.</small>
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row col-xl-12">
        <div class="form-group col-md-4">
            <button type="submit" class="btn btn-primary m-1">Update</button>
            <a asp-action="Index" asp-controller="Home" class="btn btn-dark m-1">Cancel</a>
        </div>
    </div>
    @section Scripts
        {
        <script>
                $.validator.methods.range = function (value, element, param) {
                    var globalizedValue = value.replace(",", ".");
                    return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
                }
                $.validator.methods.number = function (value, element) {
                    return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
                }
        </script>
        <script>
                $(document).ready(function () {
                    $('.custom-file-input').on("change",
                        function () {
                            var fileName = $(this).val().split("\\").pop();
                            $(this).next('.custom-file-label').html(fileName);
                        });
                });
        </script>
    }
</form>